### ISSUE TITLE
error  no find OnSearchActionListener

### ISSUE THREAD

**Issue by wkchen66** [mancj/MaterialSearchBar#1]
import android.os.Bundle;
    import android.support.v7.app.AppCompatActivity;
    import com.mancj.materialsearchbar.MaterialSearchBar;
    public class MainActivity extends AppCompatActivity  {

    private MaterialSearchBar search_bar;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        init();
    }

    private void init() {
        search_bar = (MaterialSearchBar) findViewById(R.id.search_bar);
        search_bar.setOnSearchActionListener(new MaterialSearchBar.OnSearchActionListener() {
            @Override
            public void onSearchBarClicked() {

            }

            @Override
            public void onSearchEnabled() {

            }

            @Override
            public void onSearchDisabled() {

            }

            @Override
            public void onSearch(CharSequence charSequence) {

            }

            @Override
            public void onSpeechSelected() {

            }
        });
    }
  

Why no find OnSearchActionListener error

1.add maven { url "https://jitpack.io" }    to  project level build.gradle

    // Top-level build file where you can add configuration options common to all sub-projects/modules.

    buildscript {
        repositories {
            jcenter()
        }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    }

    allprojects {
        repositories {
            jcenter()
            maven { url "https://jitpack.io" }
        }
    }

    task clean(type: Delete) {
        delete rootProject.buildDir
    }

2.add 'com.github.mancj:MaterialSearchBar:0.1.0'    to  app  build.gradle 

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:appcompat-v7:23.4.0'
        compile 'com.github.mancj:MaterialSearchBar:0.1.0'
    }

help!!!

**Comment by mancj** [comment]
Hi! I'm sorry I did not answerr. Did you solved the problem?

**Comment by mancj** [comment]
Hello! I'm sorry, i didn't answer. In the previous version OnSearchActionListener was not public. Now I changed it. You need to update the build file.gradle and change the library version to 0.1.1 instead of 0.1.0

The dependencies section should look like this:
`compile 'com.github.mancj:MaterialSearchBar:0.1.1'`

**Comment by MuhSalmaNabila** [comment]
the app has been run success when i add recyclerview fiture but when i use search bar to filter data from recyclerview, it didn't work. Any solution?
