### ISSUE TITLE
onSearchConfirmed executed twice

### ISSUE THREAD

**Issue by Cypaubr** [mancj/MaterialSearchBar#10]
When I hit the magnifying glass on the keyboard, the onSearchConfirmed method (from OnSearchActionListener) is executed two times.
Simply with :
```
@Override
public void onSearchConfirmed(CharSequence charSequence) {
    Log.d("SEARCHED",charSequence.toString());
}
```

**Comment by mancj** [comment]
This issue fixed. Check the last commit.

**Comment by robzimpulse** [comment]
Hi @mancj, could you tag me the commit id for this fix? 
I'm still experiencing `onSearchConfirmed `executed twice.
