### ISSUE TITLE
[Feature request] Search on typing

### ISSUE THREAD

**Issue by letientai299** [mancj/MaterialSearchBar#11]
For now, the search action can only be trigger manually. I'd like trigger the search after some delay during typing. Unfortunately, with current implementation, I cannot call the listener from my subclass.

**Comment by nserguier** [comment]
Hi lentientai,

I wanted to achieve the same thing as you and I found a solution using a `TextWatcher `.
First, you create your `TextWatcher ` that will execute your code to update the search when the text changes in the `EditText`:

```
TextWatcher searchWatcher = new TextWatcher() {

        @Override
        public void beforeTextChanged(CharSequence s, int start, int count, int after) {
        }

        @Override
        public void onTextChanged(final CharSequence s, int start, int before, int count) {
            updateSearch(s);
        }

        @Override
        public void afterTextChanged(Editable s) {
        }
    };
```

Then, you get the `EditText` component from the `MaterialSearchBar ` and you attach your `TextWatcher ` to it:

```
EditText searchEdit = (EditText) mSearchBar.findViewById(com.mancj.materialsearchbar.R.id.mt_editText);
searchEdit.addTextChangedListener(searchWatcher);
```

And that's all! I hope this will solve your problem and help other people achieve this.

**Comment by letientai299** [comment]
Thank @nserguier.

Actually that what I have done. But it requires knowledge about internal implementation of the library (in this case, the ID of EditText). While that solution works, I still think that it would be better if the library itself offer such feature.

**Comment by letientai299** [comment]
@mancj May I know the reason for closing this?

**Comment by mancj** [comment]
Thought@nserguier answered your question. This is not possible in the current release.
