### ISSUE TITLE
How to remove shadow?

### ISSUE THREAD

**Issue by FranciscoJavierPRamos** [mancj/MaterialSearchBar#13]

**Comment by mancj** [comment]
you mean the shadow under the background rectangle?

**Comment by FranciscoJavierPRamos** [comment]
Yes

**Comment by mancj** [comment]
It's impossible yet

**Comment by mancj** [comment]
download the latest version of the library. Now the shadow can be removed with `setCardViewElevation(int elevation)` method

**Comment by FranciscoJavierPRamos** [comment]
+1
