### ISSUE TITLE
Titile text styling

### ISSUE THREAD

**Issue by Xtizainy** [mancj/MaterialSearchBar#137]
Hi!
Could you please provide an API how to adjust main text (mt_placeholder)? More specifically size and margin
thanks

**Comment by sajorahasan** [comment]
You can try below code:

`val constraintLayout = ((searchBar.getChildAt(0) as CardView)?.getChildAt(0) as? ConstraintLayout)
val placeholderTextView = constraintLayout?.getChildAt(1) as AppCompatTextView
val editTextView = (constraintLayout?.getChildAt(2) as LinearLayout)?.getChildAt(1) as AppCompatEditText
editTextView.textSize = 14f`

**Comment by Xtizainy** [comment]
It would be better to have specific API, not workarounds

**Comment by mancj** [comment]
You can customise it by yourself. To access mt_placeholder view, use the getPlaceHolderView method.
