### ISSUE TITLE
Can not catch event click menu item (onOptionsItemSelected)

### ISSUE THREAD

**Issue by phantuanphong** [mancj/MaterialSearchBar#14]
How to catch event click menu item (onOptionsItemSelected)?

**Comment by mancj** [comment]
```
searchBar.getMenu().setOnMenuItemClickListener(this);
```

**Comment by VeePeeMarket** [comment]
> ```java
> searchBar.getMenu().setOnMenuItemClickListener(this);
> ```

Please how can I select an option from the suggestions
