### ISSUE TITLE
No resource identifier found for attribute 'placeholder' in package

### ISSUE THREAD

**Issue by tank777** [mancj/MaterialSearchBar#18]
attribute 'placeholder' not found

**Comment by mancj** [comment]
show your code, please. how are you using this attribute?

**Comment by onyxganda** [comment]
I got the same problem here, trying to add placeholder attribute in xml `app:placeholder="Text"` doesn't work. While in java, the method `setPlaceHolder(CharSequence placeholder)` is not resolved. 
Every other public methods and xml's attributes work fine.

**Comment by mancj** [comment]
Change the dependency version in your build.gradle file.
```compile 'com.github.mancj:MaterialSearchBar:0.3.5'```

**Comment by onyxganda** [comment]
by changing the version it works. thanks
