### ISSUE TITLE
Compile exception

### ISSUE THREAD

**Issue by Sonnyzoom** [mancj/MaterialSearchBar#2]
"Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.github.mancj:MaterialSearchBar:0.1.1] 
Suggestion: use tools:overrideLibrary="com.mancj.materialsearchbar" to force usage"
Can I force usage ?

**Comment by mancj** [comment]
You have to set `minSdkVersion 16`
