### ISSUE TITLE
Menu Item not showing on search bar ?

### ISSUE THREAD

**Issue by AruLNadhaN** [mancj/MaterialSearchBar#20]
I have a single item in my menu. But the menu Icon is not shown. I'm still getting the 3 dots. How can i override it ?

**Comment by shubhdo** [comment]
@AruLNadhaN 
In menu resource file change showAsAction attribute to always like in example
e.g.
`<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:id="@+id/example"
          android:icon="@drawable/example"
          android:title="@string/example"
          android:showAsAction="always"/>`

**Comment by AruLNadhaN** [comment]
This is how my menu resource looks like

`<item android:id="@+id/menu_shopcart" android:title="@string/action_cart" app:actionLayout="@layout/menu_action_item_badge" app:showAsAction="always"/>`

**Comment by shubhdo** [comment]
@AruLNadhaN  you can try this post on stackoverflow to resolve your issue
[http://stackoverflow.com/questions/18380085/menu-items-doesnt-show-up-on-the-actionbar](url)
see if it works.

**Comment by AruLNadhaN** [comment]
Thanks. But still it is not working :(

**Comment by mancj** [comment]
you can't change the popup menu icon in MaterialSearchBar. If you need an item with a custom icon, you can set the speechMode = true and set setOnSearchActionListener. then in onButtonClicked you can handle action. here is a small example:
```java
@Override
public void onButtonClicked(int buttonCode) {
    switch (buttonCode){
        case MaterialSearchBar.BUTTON_NAVIGATION:
            drawer.openDrawer(Gravity.LEFT);
            break;
        case MaterialSearchBar.BUTTON_SPEECH:
            openVoiceRecognizer();
    }
}
```

**Comment by AruLNadhaN** [comment]
I got it! But I need to have a custom Icon near the Speech Icon ? 
How can i achieve it ?

**Comment by mancj** [comment]
It is impossible in current version.

**Comment by AruLNadhaN** [comment]
Can i atleast change the drawable of speech Icon ?

**Comment by mancj** [comment]
no, you can't. I will add this possibility soon.

**Comment by AruLNadhaN** [comment]
Thanks. I'm waiting for this feature!

**Comment by nicks258** [comment]
Is this issue is fixed @mancj @AruLNadhaN

**Comment by mancj** [comment]
Not yet. Sorry, I do not have the time to do it.

**Comment by hamsoft-uganda** [comment]
How can I listen to menu clicks when I inflate it and it appears in search box with 3 dots.
Thanks
