### ISSUE TITLE
Click of the Custom Suggestion Adapter doesn't return on the callback setSuggstionsClickListener

### ISSUE THREAD

**Issue by c4adarsh** [mancj/MaterialSearchBar#23]
Your Material Search bar implementation is awesome, but there is slight problem when i try to use it.

When I give the customSuggestionAdapter, setSuggstionsClickListener is not working. Can you please change the implementation to give call back to the click listener. 
------------------------------------------------------------------------------------------------------------------
MaterialSearchBar.java

"if (adapter instanceof DefaultSuggestionsAdapter)
            ((DefaultSuggestionsAdapter) adapter).setListener(this);"
-------------------------------------------------------------------------------------------------------------------
OR
Can you please give methods to hide the image and the cross mark in the suggestions.

I am showing a predictive search after hitting a server. So the clock image and the cross image in the view is not relevant for my implementation.
------------------------------------------------------------------------------------------------------------------

Thanks,
Adarsh

**Comment by mancj** [comment]
You must implement your own callback listeners in the case of using a custom adapter.

**Comment by c4adarsh** [comment]
Thanks.
