### ISSUE TITLE
PlaceHolder BUG?

### ISSUE THREAD

**Issue by zpc941003** [mancj/MaterialSearchBar#25]
Hi,thanks for the library.And I may find a bug.
When I disable NavButton,set placeholder and set optionMenu like:

`        searchBar.setNavButtonEnabled(false);
        searchBar.setPlaceHolder("Google Play");
        searchBar.inflateMenu(R.menu.main);`

The placeholder move to right next to the three dot(menu icon).
Here's the screen short: [link](https://drive.google.com/open?id=0B27zAwzCjsjWY2V2ZndOaW44elE).
I don't know if it's a bug or I use it in a wrong way.
Thanks.

**Comment by mancj** [comment]
I fixed this bug but not yet released a new version. See the last commit.  The new version will be released when i solve #24 issue.
