### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by Vikas237Soni** [mancj/MaterialSearchBar#27]
The following classes could not be instantiated:
- com.mancj.materialsearchbar.MaterialSearchBar (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details android.content.res.Resources$NotFoundException: Could not resolve resource value: 0xFFFAFAFA.   at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:932)   at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:919)   at android.content.res.Resources_Delegate.getColorStateList(Resources_Delegate.java:226)   at android.content.res.Resources_Delegate.getColor(Resources_Delegate.java:203)   at android.content.res.Resources.getColor(Resources.java:915)   at android.content.Context.getColor(Context.java:508)   at android.support.v4.content.ContextCompatApi23.getColor(ContextCompatApi23.java:32)   at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:432)   at com.mancj.materialsearchbar.MaterialSearchBar.setupTextColors(MaterialSearchBar.java:186)   at com.mancj.materialsearchbar.MaterialSearchBar.postSetup(MaterialSearchBar.java:176)   at com.mancj.materialsearchbar.MaterialSearchBar.init(MaterialSearchBar.java:135)   at com.mancj.materialsearchbar.MaterialSearchBar.<init>(MaterialSearchBar.java:78)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)

**Comment by mancj** [comment]
have you added the jitpack repository to build.gradle?
```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```
