### ISSUE TITLE
Sorry,How can i take Custom Suggestions Adapter list click

### ISSUE THREAD

**Issue by MichaelPanW** [mancj/MaterialSearchBar#33]
![image](https://cloud.githubusercontent.com/assets/11679652/24653069/d406f940-1966-11e7-85ff-259b098c29ad.png)
how to do event when i click "Product 1"

thanks for your help

**Comment by mancj** [comment]
You need to set the `OnClickListener` to your ViewHolder's root view.
example:  http://stackoverflow.com/questions/24471109/recyclerview-onclick

**Comment by MichaelPanW** [comment]
Thank you for your answer

The last model to use is:

 recyclerView.addOnItemTouchListener
