### ISSUE TITLE
(Question) How change PopupMenu Style!

### ISSUE THREAD

**Issue by IRMobydick** [mancj/MaterialSearchBar#34]
Hi there, I've tried to change SearchBar Menu style by using style, but does not work!
I'm using search bar in fragment, my parent activity style is like this:

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="android:itemTextAppearance">@style/itemTextStyle.AppTheme</item>

        <item name="android:popupMenuStyle">@style/PopupMenu</item>
        <item name="android:textAppearanceLargePopupMenu">@style/PopupMenuTextAppearanceLarge</item>
        <item name="android:textAppearanceSmallPopupMenu">@style/PopupMenuTextAppearanceSmall</item>

    </style>

    <style name="itemTextStyle.AppTheme" parent="@android:style/TextAppearance.Widget.IconMenu.Item">
        <item name="android:textColor">@color/iconColor</item>
        <item name="android:textSize">@dimen/h3</item>
    </style>

    
    <style name="PopupMenu" parent="@style/Widget.AppCompat.Light.PopupMenu">
        <item name="android:popupBackground">@android:color/white</item>
        <item name="android:textColor">@color/iconColor</item>
        <item name="android:textSize">@dimen/h3</item>
    </style>
    <style name="PopupMenuTextAppearanceSmall" parent="@style/TextAppearance.AppCompat.Light.Widget.PopupMenu.Small">
        <item name="android:textColor">@color/iconColor</item>
        <item name="android:textSize">@dimen/h3</item>
    </style>
    <style name="PopupMenuTextAppearanceLarge" parent="@style/TextAppearance.AppCompat.Light.Widget.PopupMenu.Large">
        <item name="android:textColor">@color/iconColor</item>
        <item name="android:textSize">@dimen/h0</item>
    </style>
    

How can do that?

**Comment by IRMobydick** [comment]
Done!

    /**
     * Inflate menu for searchBar
     * @param menuResource - menu resource
     */
    public void inflateMenu(int menuResource, int popupMenuStyle){
        this.menuResource = menuResource;
        if (menuResource > 0){
            ImageView menuIcon = (ImageView) findViewById(R.id.mb_menu);
            RelativeLayout.LayoutParams params = (LayoutParams) searchIcon.getLayoutParams();
            //params.rightMargin = (int) (36*destiny);
            searchIcon.setLayoutParams(params);
            menuIcon.setVisibility(VISIBLE);
            menuIcon.setOnClickListener(this);

            Context wrapper = new ContextThemeWrapper(getContext(), popupMenuStyle);
            popupMenu = new PopupMenu(wrapper, menuIcon);
            popupMenu.inflate(menuResource);
            popupMenu.setGravity(Gravity.RIGHT);

            if (!navButtonEnabled) {
                RelativeLayout.LayoutParams params2 = (LayoutParams) searchIcon.getLayoutParams();
                params2.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
                params2.addRule(RelativeLayout.LEFT_OF, 0);
                searchIcon.setLayoutParams(params2);
            }
        }
    }


in fragment or any where else:

    mSearchBar = (MobySearchBar) view.findViewById(R.id.search_bar);
    mSearchBar.setPlaceHolder(R.mipmap.searchbar_logo);
    mSearchBar.inflateMenu(R.menu.main, R.style.PopupMenu);
    mSearchBar.setTypeface(AndroidUtilities.getTypeface(Constants.fontLight));

**Comment by mancj** [comment]
Hi. Could you pull-request your changes, please?

**Comment by IRMobydick** [comment]
Hi there, yap! at the earliest possible moment :)
