### ISSUE TITLE
EditText cursor color

### ISSUE THREAD

**Issue by Snowda** [mancj/MaterialSearchBar#35]
Currently the cursor for the EditText box for me is defaulting to white due to our apps theme but I want to set the color of the cursor in the search bar specifically so it can actually appear clearly over its white background. Any chance of getting access to the textCursorDrawable() method or something similar to the Hint and Text color methods?

**Comment by mancj** [comment]
No, there are no methods that change the color of the cursor. It depends on your `colorAccent`. 
To change the text or hint colors use `setTextHintColor` and `setTextColor` methods

**Comment by Snowda** [comment]
While I cannot change the `colorAccent` as it is used elsewhere and _needs_ to be white, I ended up finding a hack by setting `colorControlActivated` instead and defining custom styles for the activities that use the search bar. Would have been a lot cleaner if access was provided similar to `setTextHintColor` and `setTextColor` as I am already using those happily without issue. Hopefully I don't run into style conflicts down the line.
