### ISSUE TITLE
Failed to resolve: com.github.mancj:MaterialSearchBar:0.7.1

### ISSUE THREAD

**Issue by dinukapj** [mancj/MaterialSearchBar#42]
I get this error when syncing the gradle after adding `compile 'com.github.mancj:MaterialSearchBar:0.7.1'` to my gradle. What's the reason for this?

Message:
```
Failed to resolve: com.github.mancj:MaterialSearchBar:0.7.1
```

**Comment by GitUser4732** [comment]
Did you perhaps forget this step?

add this code to the the project level build.gradle file

allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}

**Comment by dinukapj** [comment]
Yes that was the issue. Thank you @GitUser4732
