### ISSUE TITLE
how to disable SearchBar by touch outside

### ISSUE THREAD

**Issue by IRMobydick** [mancj/MaterialSearchBar#45]
Hi there
Is there any way to disable searchbar by touching outside of `SearchBar`?
of course outside of Searchbar and suggestion list

**Comment by mancj** [comment]
Hello!
You need to implement this yourself.

**Comment by IRMobydick** [comment]
For who may have this issue:

1. Add `getCardView` as public in `MaterialSearchBar.java` like this:

        public View getCardView(){
            CardView cardView = (CardView) findViewById(R.id.mb_container);
            return cardView;
        }

2. Implement `dispatchTouchEvent` on activity and check touch happened inside or outside:

        @Override
        public boolean dispatchTouchEvent(MotionEvent motionEvent) {

            if (mSearchBar != null && mSearchBar.isSearchEnabled()){

                if (motionEvent.getAction() == MotionEvent.ACTION_DOWN){

                    Rect outRect = new Rect();
                    mSearchBar.getCardView().getGlobalVisibleRect(outRect);
                    if (!outRect.contains((int)motionEvent.getRawX(), (int)motionEvent.getRawY())) {
                        AndroidUtilities.hideKeyboard(mSearchBar); // This is utility to hide keyboard ;)
                        resetSearchBar();
                    }

                }

            }
            return super.dispatchTouchEvent(motionEvent);
        }

3. And finally `resetSearchBar()` is this:

        private void resetSearchBar(){
            mSearchBar.clearFocus();
            mSearchBar.hideSuggestionsList();
            mSearchBar.disableSearch();
        }
