### ISSUE TITLE
Result list not shown

### ISSUE THREAD

**Issue by OrlandoSmits** [mancj/MaterialSearchBar#48]
Hi Guys, 

My search won't return a resultlist. I see my results in the monitor but the resultlist from the searchView won't open. Do you guys have any idea what can be the issue?

` mSearchView = (MaterialSearchBar) view.findViewById(R.id.kvk_floating_search_view);

        mSearchView.setOnSearchActionListener(this);

        mSearchView.setTextColor(R.color.colorPrimary);
        mSearchView.setBackgroundColor(getActivity().getResources().getColor(R.color.colorBackground));

        LayoutInflater inflater = (LayoutInflater) getActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        mSearchAdapter = new KvkSearchAdapter(inflater);
        mSearchAdapter.setSuggestions(mCompanyList);
        mSearchView.setCustomSuggestionAdapter(mSearchAdapter);`

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.mancj.materialsearchbar.MaterialSearchBar
        android:id="@+id/kvk_floating_search_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:mt_hint="Naam, Adres of KvK"
        app:mt_maxSuggestionsCount="10"
        app:mt_placeholder="Naam, Adres of KvK"
        app:mt_speechMode="false"/>

</LinearLayout>`

**Comment by PoriLisa** [comment]
I have also same issue
