### ISSUE TITLE
BUTTON_BACK not available

### ISSUE THREAD

**Issue by tinyCoder32** [mancj/MaterialSearchBar#55]
Hi, I used the available example, there is 

> MaterialSearchBar.BUTTON_BACK

It is not available in the library that on "jitpack" 0.7.1
But i see it in the latest version of code here, i didn't know how to implement the library in my app manually, when will the jitpack library get updated?

Thanks,

**Comment by GitUser4732** [comment]
The Readme/Documentation has been updated but mancj has not created a new release since. For now you can use my Temporary Release below which is up to date with the Readme/Documentation.

`compile 'com.github.GitUser4732:MaterialSearchBar:v0.8-beta'`
