### ISSUE TITLE
Close keyboard on submit?

### ISSUE THREAD

**Issue by tinyCoder32** [mancj/MaterialSearchBar#58]
Hi, shouldn't the keyboard get closed on search submit?

**Comment by thyerrimezzari** [comment]
Hi, do this:
`
@Override
            public void onSearchConfirmed(CharSequence text) {
                // Close Keyboard
                InputMethodManager imm = (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);
                imm.hideSoftInputFromWindow(materialSearchBar.getWindowToken(), 0);
            }
`
