### ISSUE TITLE
Possible to focus the search bar programmatically?

### ISSUE THREAD

**Issue by jakelauer** [mancj/MaterialSearchBar#67]
I attempted to use `requestFocus()` on the MaterialSearchBar view, but it doesn't focus it the same way clicking on it does.

**Comment by mancj** [comment]
Use `enableSearch()` to focus search view

**Comment by jakelauer** [comment]
@mancj Nice, that works to focus the search. However, it looks like I can't unfocus the search except by using disableSearch(), which hides the search text.

**Comment by jakelauer** [comment]
@mancj Nevermind, I was able to requestfocus() on another element to solve that issue.
