### ISSUE TITLE
Failed To Resolve com.github.mancj:MaterialSearchBar:0.7.6

### ISSUE THREAD

**Issue by kunwarshekhar** [mancj/MaterialSearchBar#69]
i have added this code to the project level build.gradle file still facing the issue .
allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}

**Comment by mancj** [comment]
Try again, I added a new release

**Comment by kunwarshekhar** [comment]
Still the same issue .

**Comment by shubhamkhuteta** [comment]
i' also facing the same issue.
 please help me.

**Comment by Syetchau** [comment]
Hello, before today, the mancj.searchBar is working fine. However, I cannot sync my project with the mancj.searchBar library. Already add      
   maven { url "https://jitpack.io" }  long time ago.
