### ISSUE TITLE
Failed to resolve: com.github.mancj:MaterialSearchBar:0.2.1 

### ISSUE THREAD

**Issue by MuhSalmaNabila** [mancj/MaterialSearchBar#7]
when I make app with your instruction to add compile 'com.github.mancj:MaterialSearchBar:0.2.1', I found error while gradling project

**Comment by kylm53** [comment]
add this code to the the project level build.gradle file

allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}

**Comment by kylm53** [comment]
@MuhSalmaNabila 
add this code to the the project level build.gradle file

allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}

**Comment by MuhSalmaNabila** [comment]
that's work !
thanks

**Comment by MuhSalmaNabila** [comment]
Can I use method openVoiceRecognizer(); to make searching fiture with voice like google play store search bar?

**Comment by mancj** [comment]
no, this is just an example. you need to write your own method for that
