### ISSUE TITLE
The suggestions do not collapsed when suggestions list is empty

### ISSUE THREAD

**Issue by LeonardoReMake** [mancj/MaterialSearchBar#71]
I receive the list of suggestions in activity from the web. Then call `setSuggestions(List<Entity>)` from `SuggestionsAdapter`. When I receive empty list, try to call `clearSuggestions()`, but the suggestions panel remains on its spot. 
<img width="484" alt="2018-04-01 18 27 29" src="https://user-images.githubusercontent.com/5832758/38174717-6d68c8a8-35da-11e8-8a3e-d180fee92e8e.png">

Setting the list of suggestions:
```
if (suggestions == null) {
 locationSuggestionAdapter.clearSuggestions(); // do not hide the panel
 return;
}
```

**Comment by rhlmshr** [comment]
Just implement a check for that condition like this:
```
if (suggestions == null) {
 locationSuggestionAdapter.disableSearch() ;
 return;
}
```
Hope this would help.
